name: Deploy - Front-end

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

      - name: Instalar Dependências
        run: npm install

      - name: Build da Aplicação
        run: npm run build

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u velipefieira --password-stdin    

      - name: Build e Push da Imagem Docker
        run: |
          docker build -t velipefieira/frontend:latest -f Dockerfile .
          docker push velipefieira/frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy na instância EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.IP_FRONT }}
          username: ubuntu
          key: ${{ secrets.KEY_FRONT }}
          script: |
            sudo docker pull velipefieira/frontend:latest
            sudo docker stop frontend || true
            sudo docker rm frontend || true
            sudo docker run -d --name frontend -p 80:80 velipefieira/frontend:latest
