name: SonarCloud Scan // Nome do arquivo

on:
  push:
    branches:
      - testes-sonar
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - testes-sonar

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: npm install

      - name: Run SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonar-scanner -Dsonar.projectKey=Equipe-CodeLand_API-2024.2-Front-End -Dsonar.organization=equipe-codeland -Dsonar.host.url=https://sonarcloud.io
          
      - name: Check Quality Gate
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=Equipe-CodeLand_API-2024.2-Front-End" | jq -r '.projectStatus.status')
          echo "Quality Gate Status: $STATUS"
          if [ "$STATUS" != "OK" ]; then
            echo "Quality Gate failed!"
            exit 1
          fi